apiVersion:              v1
kind:                    Service
metadata:
  namespace:             hellopy-ns
  name:                  hello-python-service
spec:
  selector:
    app:                 hello-python
  ports:
  - protocol:            "TCP"
    port:                6001
    targetPort:          5000
  type:                  LoadBalancer
